version: '2'
services:
  redis_order:
    image: sickp/alpine-redis:3.2.2
    ports:
      - "6379:6379"

  percona_users:
    image: percona/percona-server:8.0
    ports:
      - "3308:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - v-users:/var/lib/mysql

volumes:
  v-users:
